Update installation page
redhat-developer/odo pull request #5371
Opened 2022-01-20 18:54 UTC by cdrage

**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**

Updates the installation page with the following:
- Reorganizes some wording with regards to where changes of the release
are, architectures, etc.
- Moves the IDE portion into a separate section so it's better to
navigate via the sidebar
- Moves the "building from source" to the CLI Binary part as it relates
to CLI rather than IDE

**Which issue(s) this PR fixes:**

N/A

**PR acceptance criteria:**

- [X] Unit test

- [X] Integration test

- [X] Documentation

**How to test changes / Special notes to the reviewer:**

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2022-01-21 15:55 UTC, cdrage commented
More updates!

- Changes to the installation page to favour tabbed installation pages instead of the script that we previously used
- Steps to verify the downloaded binary with the SHA-256 sum
- Removed section from Windows with regards to setting `PATH` as it is forever changing. Recent Windows 10 update has changed the location. Windows 11 is different. Windows 7/8 is different too. At this point it is implied that the user already knows how / can google it.

There are now different suggested ways to install binaries from k8s projects:
- For Linux it is recommended to use `sudo install` and suggest a way to use the binary on non-root-access machines.
- For MacOS the normal reccomendation of copying to /usr/bin/ is still reccomended.
- For Windows I have suggested using powershell to install
- 
Ready for another review @dharmit @kadel @feloy

2022-01-21 16:44 UTC, dharmit requested changes
Totally nitpicking. Sorry about it. :)

2022-01-21 16:44 UTC, dharmit commented on docs/website/docs/getting-started/installation.md
> +`odo` can be used as either a [CLI tool](/docs/getting-started/installation#cli-binary-installation) or a [IDE plugin](/docs/getting-started/installation#ide-installation) on Mac, Windows or Linux.
```suggestion
`odo` can be used as either a [CLI tool](/docs/getting-started/installation#cli-binary-installation) or an [IDE plugin](/docs/getting-started/installation#ide-installation) on Mac, Windows or Linux.
```

2022-01-24 12:30 UTC, kadel commented
/approec

2022-01-24 13:12 UTC, merged