Add --hostname alias to odo url create
redhat-developer/odo pull request #5394
Opened 2022-01-26 14:38 UTC by cdrage

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

This adds the --hostname alias to the `odo url create` command since
similar tools such as `oc` use `--hostname` to create routes, and thus
a user may accidently enter --hostname instead.

This PR also reorganized the help usage so it's more inline with
"building up" on each example.

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/5379

**PR acceptance criteria:**

- [ ] Unit test

N/A

- [ ] Integration test

N/A

- [X] Documentation

**How to test changes / Special notes to the reviewer:**

N/A

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2022-01-26 14:59 UTC, kadel commented on pkg/odo/cli/url/create.go
> +	urlCreateCmd.Flags().MarkHidden("hostname")
If it is hidden why even have it? I think that this is just creating confusion.

2022-01-27 12:49 UTC, dharmit requested changes

2022-01-27 12:49 UTC, dharmit commented on pkg/odo/cli/url/create.go
> +	// Alias for `--host` in case someone where to enter --hostname by mistake, and then mark it as hidden.
```suggestion
	// Alias for `--host` in case someone were to enter --hostname by mistake, and then mark it as hidden.
```

2022-01-27 13:02 UTC, dharmit commented
/lgtm
/approve

2022-01-27 16:04 UTC, merged