Test and fix using namespace from env file
redhat-developer/odo pull request #5545
Opened 2022-03-11 14:32 UTC by feloy

**What type of PR is this:**

/kind bug
/kind tests

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5544 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-03-11 14:33 UTC, feloy commented
@kadel could you please check that these tests respect the specs?

2022-03-14 03:56 UTC, valaparthvi requested changes

2022-03-14 03:56 UTC, valaparthvi commented on tests/integration/devfile/cmd_devfile_deploy_test.go
> +				stdout = helper.Cmd("odo", "deploy").AddEnv("PODMAN_CMD=echo").ShouldPass().Out()
You haven't added the `env.yaml` exists, and the project check here.

2022-03-14 03:56 UTC, valaparthvi commented on tests/integration/devfile/cmd_devfile_deploy_test.go
> +					commonVar.CliRunner.SetProject(otherNS)
`CreateRandNamespaceProject` creates and sets the project name.

2022-03-14 03:56 UTC, valaparthvi commented on tests/integration/devfile/cmd_dev_test.go
> +					commonVar.CliRunner.SetProject(otherNS)
Same comment as below.

2022-03-14 09:36 UTC, valaparthvi approved these changes

2022-03-14 09:36 UTC, valaparthvi commented
/approve

2022-03-14 10:21 UTC, feloy commented
/hold

2022-03-14 12:50 UTC, merged