remove odo catalog command
redhat-developer/odo pull request #5577
Opened 2022-03-21 14:32 UTC by kadel

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**
- remove `odo catalog` command 
- move devfile registry relevant code to pkg/registry
- removed page about `odo catalog` from docs
- updated docs for `odo init` to not mention `odo catalog`

There is still documentation that mentions `odo catalog` command but that in quick start page, setup or pages about other commands. Those should be addressed in PRs for that command, or in a separate effort to alight docs with v3-alpha1

**Which issue(s) this PR fixes:**

Fixes #5562

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-03-22 11:05 UTC, feloy requested changes

2022-03-22 11:05 UTC, feloy commented on pkg/odo/genericclioptions/clientset/clientset.go
> +		dep.InitClient = _init.NewInitClient(dep.FS, dep.PreferenceClient, dep.RegistryClient)
You will need to remove the dependency of catalog in INIT entry in `subdeps`

2022-03-22 15:00 UTC, valaparthvi requested changes
There are still remains in docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md. Other docs such as `create.md` and `service.md` still have references, but they can probably be removed in the relevant cleanup PRs.

2022-03-22 15:12 UTC, kadel commented
> There are still remains in docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md. Other docs such as `create.md` and `service.md` still have references, but they can probably be removed in the relevant cleanup PRs.

Yes, those documents need to be completely reworked. It should be done in some separate PR that will focus only on docs. 
I just wanted to remove the most obvious parts of the documentation for this in this PR

2022-03-22 15:14 UTC, valaparthvi commented
> > There are still remains in docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md. Other docs such as `create.md` and `service.md` still have references, but they can probably be removed in the relevant cleanup PRs.
> 
> Yes, those documents need to be completely reworked. It should be done in some separate PR that will focus only on docs. I just wanted to remove the most obvious parts of the documentation for this in this PR

You can still remove from the json-output.md because it is relevant and in the scope of your PR.

2022-03-22 16:15 UTC, kadel commented
> > > There are still remains in docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md. Other docs such as `create.md` and `service.md` still have references, but they can probably be removed in the relevant cleanup PRs.
> > 
> > 
> > Yes, those documents need to be completely reworked. It should be done in some separate PR that will focus only on docs. I just wanted to remove the most obvious parts of the documentation for this in this PR
> 
> You can still remove from the json-output.md because it is relevant and in the scope of your PR.

Seem a little bit pointless as that whole document is not valid for v3. We need to remove that whole file, but that I think is not relevant to the original issue this PR tries to address. I'll do that in another PR

2022-03-22 16:49 UTC, kadel commented
/retest

2022-03-22 17:02 UTC, feloy commented
/lgtm

2022-03-23 06:49 UTC, valaparthvi commented
> > > > There are still remains in docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md. Other docs such as `create.md` and `service.md` still have references, but they can probably be removed in the relevant cleanup PRs.
> > > 
> > > 
> > > Yes, those documents need to be completely reworked. It should be done in some separate PR that will focus only on docs. I just wanted to remove the most obvious parts of the documentation for this in this PR
> > 
> > 
> > You can still remove from the json-output.md because it is relevant and in the scope of your PR.
> 
> Seem a little bit pointless as that whole document is not valid for v3. We need to remove that whole file, but that I think is not relevant to the original issue this PR tries to address. I'll do that in another PR
> 
> update: opened #5585

Oh, you're right. It completely skipped my mind that we haven't implemented JSON for v3. Sorry about this.

2022-03-23 07:53 UTC, dharmit commented
```
Running oc with args [oc get pods --namespace cmd-devfile-push-test693jkd --selector=component=iwqqlu -o jsonpath={.items[*].metadata.name}]
[oc] iwqqlu-app-6f5f8747d9-74f7bRunning oc with args [oc exec iwqqlu-app-6f5f8747d9-74f7b -c runtime --namespace cmd-devfile-push-test693jkd -- ps -ef]
[oc] UID          PID    PPID  C STIME TTY          TIME CMD
[oc] 1003410+       1       0  0 18:06 ?        00:00:00 /opt/odo/bin/supervisord -c /opt/odo/conf/devfile-supervisor.conf
[oc] 1003410+      37       1  0 18:07 ?        00:00:00 /bin/sh /opt/odo/bin/devfile-command devrun
[oc] 1003410+      40      37  0 18:07 ?        00:00:00 sh -c cd /projects && mvn -Dmaven.repo.local=/data/cache/.m2/repository spring-boot:run
[oc] Signal 23 (URG) caught by ps (3.3.15).
[oc] ps:ps/display.c:66: please report this bug
[oc] command terminated with exit code 1
Deleting project: cmd-devfile-push-test693jkd 
```
Doesn't look like a real failure to me.

/test v4.10-integration-e2e
/approve

2022-03-23 11:15 UTC, merged