Create cleanup
redhat-developer/odo pull request #5589
Opened 2022-03-24 13:13 UTC by valaparthvi

**What type of PR is this:**
/kind code-refactoring

**What does this PR do / why we need it:**
This PR cleans up `odo create` and all of its references from odo.
**Which issue(s) this PR fixes:**

Fixes #5564 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**
You can review each commit independently, each one has a clear purpose.

2022-03-24 16:21 UTC, feloy requested changes

2022-03-24 16:21 UTC, feloy commented on tests/integration/devfile/cmd_devfile_push_test.go
> +			helper.Cmd("odo", "init", "--name", cmpName, "--devfile-path", helper.GetExamplePath("source", "devfiles", "nodejs", "devfile-registry.yaml")).ShouldPass()
Feel free to completely remove all the problematic tests from this file (or all the file), as this file will be removed in the other PR #5570

2022-03-24 16:21 UTC, feloy commented on tests/integration/devfile/cmd_devfile_url_test.go
> +	"github.com/redhat-developer/odo/tests/helper"
Feel free to remove this file, as it will be removed from the other PR #5561

2022-03-24 16:21 UTC, feloy commented on tests/integration/devfile/cmd_dot_devfile_test.go
> +	// We continued iterating on bracket pair guides. Horizontal lines now outline the scope of a bracket pair. Also, vertical lines now depend on the indentation of the code that is surrounded by the b
You can also remove this file

2022-03-24 18:58 UTC, cdrage commented
Hey  @valaparthvi I'm going to close https://github.com/redhat-developer/odo/pull/5575 as your PR directly influences. I'll keep yours open instead as you did a much better job cleaning up the tests!

2022-03-25 10:02 UTC, valaparthvi commented
/override ci/prow/v4.10-integration-e2e 

IBM cloud test passes for both K8s and OC.

2022-03-25 12:16 UTC, cdrage commented
Tests pass, code looks good!

/lgtm

2022-03-25 12:35 UTC, feloy commented
/approve

2022-03-25 12:37 UTC, merged