[wip] Fix flaky test "should expose two endpoints on localhost"
redhat-developer/odo pull request #5599
Opened 2022-03-29 08:35 UTC by feloy

**What type of PR is this:**

/kind tests

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-03-30 02:08 UTC, feloy commented
IBM tests passed 6x in a row

2022-03-30 08:33 UTC, rm3l reviewed
Nice way of fixing the issue 👍🏿 
I saw that this test in `tests/interactive/cmd_dev_test.go` was not updated to use the new `random-ports` flag: [`should run alizer to download devfile successfully even with -v flag`](https://github.com/feloy/odo/blob/fix-http-flaky-test/tests/interactive/cmd_dev_test.go#L41-L45)

Is that on purpose?

2022-03-30 08:44 UTC, feloy commented
> Nice way of fixing the issue 👍🏿 I saw that this test in `tests/interactive/cmd_dev_test.go` was not updated to use the new `random-ports` flag: [`should run alizer to download devfile successfully even with -v flag`](https://github.com/feloy/odo/blob/fix-http-flaky-test/tests/interactive/cmd_dev_test.go#L41-L45)
> 
> Is that on purpose?

No, good catch. I've added it

2022-03-30 08:56 UTC, rm3l approved these changes

2022-03-30 09:53 UTC, feloy commented
@rm3l I force pushed the commit to rerun the tests, as the OpenShift platform were not stable. Feel free to lgtm again :)

2022-03-30 10:01 UTC, rm3l commented
> @rm3l I force pushed the commit to rerun the tests, as the OpenShift platform were not stable. Feel free to lgtm again :)

/lgtm

2022-03-30 10:46 UTC, anandrkskd commented
/lgtm from test perspective

2022-03-31 10:08 UTC, valaparthvi requested changes
/approve

2022-03-31 10:08 UTC, valaparthvi commented on pkg/odo/cli/dev/dev.go
> +	devCmd.Flags().BoolVarP(&o.randomPorts, "random-ports", "f", false, "Assign random ports to redirectoed ports")
```suggestion
	devCmd.Flags().BoolVarP(&o.randomPorts, "random-ports", "f", false, "Assign random ports to redirected ports")
```

2022-03-31 12:27 UTC, valaparthvi commented
/lgtm
[4ab204d](https://github.com/redhat-developer/odo/pull/5599/commits/4ab204d1585f074dc2fb378335a7d786d3485509) was a minor change.

2022-03-31 12:31 UTC, merged