[wip] Wait deletion
redhat-developer/odo pull request #5604
Opened 2022-03-30 09:58 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5565 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-04-01 09:46 UTC, rm3l requested changes

2022-04-01 09:46 UTC, rm3l commented on pkg/kclient/owner_reference_test.go
> +		// TODO: Add test cases.
To me, it looks like all cases in `TryWithBlockOwnerDeletion` are covered, no? So we could remove this `TODO` comment, I think.

2022-04-01 09:46 UTC, rm3l commented on tests/integration/devfile/cmd_dev_test.go
> +				It("should have deleted all resources before to return", func() {
Small suggestion ;)

```suggestion
				It("should have deleted all resources before returning", func() {
```

2022-04-01 09:46 UTC, rm3l commented on pkg/component/delete/delete.go
> +func (do *DeleteComponentClient) DeleteResources(resources []unstructured.Unstructured, wait bool) []unstructured.Unstructured {
Maybe I missed it, but per the acceptance criteria in #5565, I didn't see any sensible timeout defined when `wait` is `true`:

> there should be some sensible timeout so it doesn't end in an infinite loop.

2022-04-01 09:48 UTC, rm3l commented on pkg/component/delete/delete.go
> +func (do *DeleteComponentClient) DeleteResources(resources []unstructured.Unstructured, wait bool) []unstructured.Unstructured {
Oh wait, I just saw a timeout defined in `WaitDynamicResourceDeleted`. So please ignore this comment :)

2022-04-01 14:25 UTC, rm3l approved these changes
LGTM. I tested your branch, and this new flag `--wait` worked like a charm.

One thing to note from the user perspective. No progress/output is displayed while waiting. I guess this might be problematic in the future if resource deletion takes long, until the timeout elapses. But this behavior can be fixed later.

2022-04-04 12:07 UTC, rm3l approved these changes

2022-04-04 18:35 UTC, cdrage commented
/approve

Tested and it works well here too! I didn't find any issues with the code at all.

2022-04-04 18:50 UTC, feloy commented
/retest

2022-04-04 19:46 UTC, feloy commented
/retest

2022-04-04 21:14 UTC, merged