Updates the odo dev output for logging
redhat-developer/odo pull request #5609
Opened 2022-03-30 16:52 UTC by cdrage

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**

This PR does the following:
- Removes the references to `odo log`
- Changes the output to last 100 lines and puts the number in a constant
- Reworks the output of `odo dev` a bit to be bolded / more consise with
  out outputs.

See below for the changes:
```sh
▶ copy-odo && devfiles && cd deploy-no-knative && odo dev
go build -mod=vendor -ldflags="-X github.com/redhat-developer/odo/pkg/version.GITCOMMIT=4669bc9dc" cmd/odo/odo.go
  __
 /  \__     Developing using the deploy-no-knative Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v2.5.0
 \__/

↪ Deploying to the cluster in developer mode
 ✓  Waiting for Kubernetes resources [360ms]
 ✓  Syncing files into the container [1ms]
 ✓  Building your application in container on cluster [1s]
 ✓  Executing the application [1s]
 ⚠  Devfile command "run" exited with an error status in 1 seconds
 ⚠  Last 100 lines of log:
time="2022-03-30T16:47:25Z" level=info msg="try to start program" program=devrun
time="2022-03-30T16:47:25Z" level=info msg="success to start program" program=devrun
ODO_COMMAND_RUN is npm start
Changing directory to /project
Executing command cd /project && npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /project/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/project/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
...
time="2022-03-30T16:50:30Z" level=info msg="Don't start the stopped program because its retry times 0 is greater than start retries 0" program=devrun
Your application is now running on the cluster.

- Port 3000 from "runtime" container forwarded to localhost:40001

Watching for changes in the current directory /Users/cdrage/syncthing/dev/k8s/devfiles/deploy-no-knative

Press Ctrl+c to exit.
```

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/5606

**PR acceptance criteria:**

- [X] Unit test

- [X] Integration test

- [X] Documentation

**How to test changes / Special notes to the reviewer:**

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2022-03-30 20:12 UTC, cdrage commented
/retest

2022-03-31 04:25 UTC, valaparthvi requested changes
Code lgtm.
Can you also add an integration test case asserting this change?

2022-03-31 12:58 UTC, cdrage commented
@valaparthvi since this is documentation / UI / UX changes I won't be writing an integration test for this case :)

2022-03-31 13:20 UTC, cdrage commented
I have resolved the conflicts. 

`odo dev` now looks like this:

Let me know what you think @valaparthvi @kadel @dharmit 

I have added some code comments as to *why* that we are using green + bold for the port forwarding. It imitates the UX/UI design of a few other similar tools that use port forwarding.

![Screen Shot 2022-03-31 at 9 19 08 AM](https://user-images.githubusercontent.com/6422176/161064217-39e6517d-304c-4b30-8db3-321a9848d068.png)

2022-04-07 05:05 UTC, valaparthvi commented
/approve
Code lgtm, but can you fix the failing tests- https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5609-openshift-tests-1235.txt?

2022-04-08 18:44 UTC, feloy commented
/lgtm

2022-04-08 18:46 UTC, merged