Remove references to v2 commands, remove unused functions, and constants
redhat-developer/odo pull request #5638
Opened 2022-04-06 17:46 UTC by valaparthvi

**What type of PR is this:**
/kind code-refactoring

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5636 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
1. Used Goland editor inspection tool to identify unused functions, and constants.

2022-04-08 07:48 UTC, feloy commented
As we will rewrite many commands that were existing in v2 and that have been removed for the time being, I would prefer not to remove the utility functions that are not used now but will most probably be helpful when we will write the new commands.

I would prefer to delete these ones when we are done with v3.

2022-04-11 09:19 UTC, valaparthvi commented
> As we will rewrite many commands that were existing in v2 and that have been removed for the time being, I would prefer not to remove the utility functions that are not used now but will most probably be helpful when we will write the new commands.
> 
> I would prefer to delete these ones when we are done with v3.

Can you point out the functions? A few at least?

2022-04-11 11:06 UTC, feloy commented
> > As we will rewrite many commands that were existing in v2 and that have been removed for the time being, I would prefer not to remove the utility functions that are not used now but will most probably be helpful when we will write the new commands.
> > I would prefer to delete these ones when we are done with v3.
> 
> Can you point out the functions? A few at least?

Here are some functions I think it would be interesting to keep for the moment:

- `GetProjectTypeFromDevfileMetadata`
- `GetLanguageFromDevfileMetadata` to be exhaustive on `Get*FromDevfileMetadata`
- `PreStart DevfileEventType = "preStart"` and other event types to be exhuastive
- all methods in `pkg/log/status.go` to have more choices on displaying output

2022-04-11 12:20 UTC, valaparthvi commented
> > > As we will rewrite many commands that were existing in v2 and that have been removed for the time being, I would prefer not to remove the utility functions that are not used now but will most probably be helpful when we will write the new commands.
> > > I would prefer to delete these ones when we are done with v3.
> > 
> > 
> > Can you point out the functions? A few at least?
> 
> Here are some functions I think it would be interesting to keep for the moment:
> 
>     * `GetProjectTypeFromDevfileMetadata`
> 
>     * `GetLanguageFromDevfileMetadata` to be exhaustive on `Get*FromDevfileMetadata`
> 
>     * `PreStart DevfileEventType = "preStart"` and other event types to be exhuastive
> 
>     * all methods in `pkg/log/status.go` to have more choices on displaying output

I removed the Get*FromDevfileMetadata methods because they were added IIRC to add them to telemetry data, I do not believe they would be useful someplace else.

The devfile events have been around for a long time and they haven't been put to use, so I removed them. And they're anyway constants, we can add them back with v2 as a reference.

About methods in `pkg/log/status.go`, they've been around for quite sometime(even during v2)  in an unused state. The new commands have a different UI/UX, I figured we would write new methods as and when required.

2022-04-11 12:47 UTC, feloy commented
/lgtm

2022-04-14 03:35 UTC, valaparthvi commented
@feloy Can you lgtm again? I had to rebase.

2022-04-14 06:24 UTC, feloy approved these changes

2022-04-18 08:21 UTC, dharmit requested changes
/approve

2022-04-18 08:21 UTC, dharmit commented on pkg/component/component.go
>  // GetProjectTypeFromDevfileMetadata returns component type from the devfile metadata
Please delete the comment for the function that was removed.

2022-04-18 08:21 UTC, dharmit commented on pkg/component/component.go
>  // GetLanguageFromDevfileMetadata returns component type from the devfile metadata
Please delete the comment for the function that was removed.

2022-04-18 08:21 UTC, dharmit commented on pkg/devfile/image/image.go
> +func BuildPushSpecificImage(devfilePath string, component devfile.Component, push bool) error {
Can you update the function's comment since we are removing `devfileObj`?

2022-04-19 08:44 UTC, dharmit commented
/lgtm

2022-04-19 10:27 UTC, valaparthvi commented
/retest-required

2022-04-20 04:52 UTC, valaparthvi commented
/override Kubernetes Integration Tests/Kubernetes Integration Tests

2022-04-20 04:52 UTC, valaparthvi commented
/override Unit Tests/Unit Tests
IBM test passes.

2022-04-20 04:54 UTC, merged