Odo init json main
redhat-developer/odo pull request #5658
Opened 2022-04-13 07:50 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

Adds JSON output to odo init command

**Which issue(s) this PR fixes:**

Fixes #5645 

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-04-14 03:35 UTC, valaparthvi requested changes

2022-04-14 03:35 UTC, valaparthvi commented on pkg/odo/cli/init/init.go
> +	}
Can you replace this with `libdevfile.HasDeployCommand()` method?
```suggestion
	if libdevfile.HasDeployCommand(devfileObj.Data) {
		exitMessage += "\nTo deploy your component to a cluster use \"odo deploy\"."
	}
```

2022-04-14 11:05 UTC, valaparthvi commented on pkg/odo/cli/init/init.go
> +		ManagedBy:      "odo",
Can you also add these fields in the JSON output in the docs?

2022-04-15 07:50 UTC, rm3l approved these changes

2022-04-19 10:38 UTC, valaparthvi commented
/approve

2022-04-19 11:40 UTC, merged