`odo dev --debug`
redhat-developer/odo pull request #5664
Opened 2022-04-14 06:48 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5583 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-04-18 12:07 UTC, dharmit requested changes

2022-04-19 20:06 UTC, cdrage reviewed
Super small edits, otherwise, the code LGTM / works well for me!

2022-04-19 20:06 UTC, cdrage commented on pkg/odo/cli/dev/dev.go
> +	devCmd.Flags().BoolVar(&o.debugFlag, "debug", false, "Execute the debug command to start the component inside container")
Bit of an odd sentence. Maybe: `Excecute the debug command within the component` ?

2022-04-19 20:06 UTC, cdrage commented on pkg/watch/watch.go
> +func addRecursiveWatch(watcher *fsnotify.Watcher, topPath string, path string, ignores []string) error {
unsure if topPath is a spelling error or not either? should it be toPath?

2022-04-21 16:22 UTC, rm3l reviewed
Maybe I missed something while reading the issues this PR is supposed to fix (both https://github.com/redhat-developer/odo/issues/5583 and https://github.com/redhat-developer/odo/issues/4389), but it looks like they are not related (although https://github.com/redhat-developer/odo/issues/4389#issuecomment-1098863359 talks about fixing the issue for `odo dev` as well).
Wouldn't it be better to have 2 separate PRs instead, to make it easier to review both (and also read the Git history)?

2022-04-25 08:44 UTC, feloy commented on pkg/watch/watch.go
> +func addRecursiveWatch(watcher *fsnotify.Watcher, topPath string, path string, ignores []string) error {
I changed to `rootPath` to avoid confusion, and documented it

2022-04-25 08:46 UTC, feloy commented on pkg/watch/watch.go
> +			watchError = fmt.Errorf("unable to get relative path of %q on %q", event.Name, path)
I can see it used in 
```
if e := addRecursiveWatch(watcher, path, event.Name, fileIgnores); e != nil && watchError == nil {
```

2022-04-25 08:57 UTC, feloy commented
> Maybe I missed something while reading the issues this PR is supposed to fix (both #5583 and #4389), but it looks like they are not related (although [#4389 (comment)](https://github.com/redhat-developer/odo/issues/4389#issuecomment-1098863359) talks about fixing the issue for `odo dev` as well). Wouldn't it be better to have 2 separate PRs instead, to make it easier to review both (and also read the Git history)?

I fixed #4389 in this PR because `odo dev --debug` is quite unusable without it.

But it will be simpler to review and for history if I split them, I'll make a separate PR for #4389

2022-04-25 11:23 UTC, feloy commented
Closed in favor of #5690 + #5689

2022-04-25 11:23 UTC, closed without merging