odo dev --debug
redhat-developer/odo pull request #5690
Opened 2022-04-25 11:23 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5583 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-04-25 13:10 UTC, rm3l requested changes

2022-04-25 13:10 UTC, rm3l commented on tests/integration/devfile/cmd_dev_debug_test.go
> +
Would it make sense to also add a test case for Devfiles that do not define any debug command? The behavior from what I've seen in this PR is to make `odo` exit with an error message.

2022-04-26 08:14 UTC, rm3l approved these changes

2022-04-26 10:35 UTC, dharmit requested changes

2022-04-26 11:19 UTC, dharmit commented
@feloy in the past when we were working on debug mode, we used to consider testing things using VS Code `launch.json` and connecting to the port on which the app's debug mode port is listening.

For this PR, I downloaded the devfile in the tests of this PR, but can't really connect to it. Or, maybe, VS Code is connecting to it, but I don't know what to do. Also, I have never worked with websockets myself, so maybe I'm doing it completely wrong.

Do you think you can share the steps you followed to test the debug mode yourself?

I spent some time on it, but still feel dumb about this thing (how to test debug mode functionality.)

2022-04-26 13:11 UTC, feloy commented
> @feloy in the past when we were working on debug mode, we used to consider testing things using VS Code `launch.json` and connecting to the port on which the app's debug mode port is listening.
> 
> For this PR, I downloaded the devfile in the tests of this PR, but can't really connect to it. Or, maybe, VS Code is connecting to it, but I don't know what to do. Also, I have never worked with websockets myself, so maybe I'm doing it completely wrong.
> 
> Do you think you can share the steps you followed to test the debug mode yourself?
> 
> I spent some time on it, but still feel dumb about this thing (how to test debug mode functionality.)

@dharmit It should be the exact same way as with odo v2. If you follow the steps described in this blog post (Debugging the micro-service), it should work: https://dev.to/feloy/odo-a-tool-to-simplify-development-on-kubernetes-5c9a

To test with the files used in the integration test, you can get the launch.json from the blog post, then run a Debug session and set a Breakpoint where a request is replied (on the `res.send('Hello from Node.js Starter Application!');` for example). Then you execute a request on your app endpoint (`curl 127.0.0.1:40001`) and vscode should pop up and show your program interrupted on your breakpoint

2022-04-27 07:12 UTC, dharmit commented
> To test with the files used in the integration test, you can get the launch.json from the blog post, then run a Debug session and set a Breakpoint where a request is replied (on the `res.send('Hello from Node.js Starter Application!');` for example). Then you execute a request on your app endpoint (`curl 127.0.0.1:40001`) and vscode should pop up and show your program interrupted on your breakpoint

@feloy I am doing something wrong, it seems.

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "odo dev debug",
            "program": "${workspaceFolder}/server.js",
            "address": "localhost",
            "port": 40002,
            "localRoot": "${workspaceFolder}",
        }
    ]
}
```
I have added breakpoints at both the lines in the `server.js` that have `Hello from Node.js ` in them. I run `odo dev --debug`, then I start debugging session from VS Code, and finally do `curl localhost:40001`/`curl localhost:40002`. Neither of them takes me to the breakpoint.

The feeling of dumbness is getting real bad at this point, so I'll approve since I don't want my limitation to block your PR.

/approve
/lgtm

2022-04-27 07:28 UTC, feloy commented
> > To test with the files used in the integration test, you can get the launch.json from the blog post, then run a Debug session and set a Breakpoint where a request is replied (on the `res.send('Hello from Node.js Starter Application!');` for example). Then you execute a request on your app endpoint (`curl 127.0.0.1:40001`) and vscode should pop up and show your program interrupted on your breakpoint
> 
> @feloy I am doing something wrong, it seems.
> 
> `launch.json`:
> 
> ```json
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "node",
>             "request": "attach",
>             "name": "odo dev debug",
>             "program": "${workspaceFolder}/server.js",
>             "address": "localhost",
>             "port": 40002,
>             "localRoot": "${workspaceFolder}",
>         }
>     ]
> }
> ```
> 
> I have added breakpoints at both the lines in the `server.js` that have `Hello from Node.js ` in them. I run `odo dev --debug`, then I start debugging session from VS Code, and finally do `curl localhost:40001`/`curl localhost:40002`. Neither of them takes me to the breakpoint.
> 
> The feeling of dumbness is getting real bad at this point, so I'll approve since I don't want my limitation to block your PR.
> 
> /approve /lgtm

Can you try with this launch.json (remoteRoot added):

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to remote 5858",
            "type": "node",
            "request": "attach",
            "address": "localhost",
            "port": 40002,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/projects"
        }
    ]
}
```

2022-04-27 08:38 UTC, feloy commented
/override ci/prow/v4.10-integration-e2e

IBM Could tests pass

2022-04-27 08:40 UTC, merged

2022-04-27 09:04 UTC, dharmit commented
> Can you try with this launch.json:

That works. Thanks!

It works when I curl the port 40001, not 40002. However, the debug port 5858 is forwarded to 40002:
```
Your application is now running on the cluster
 - Forwarding from 127.0.0.1:40001 -> 3000
 - Forwarding from 127.0.0.1:40002 -> 5858
```
I think I need to use websockets instead of http when trying to work with 40002, right?

2022-04-27 09:16 UTC, feloy commented
Port 5858 (and 40002) are for the debugger only, for it to be able to communicate with the process inside the container. You, as a developer, don't need to use it directly.

2022-04-27 09:41 UTC, dharmit commented
OK, thanks for guiding me patiently. I surely need some debugging 101 class/course. 😞