[wip] odo describe component
redhat-developer/odo pull request #5725
Opened 2022-05-10 08:51 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5661 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-05-10 19:31 UTC, valaparthvi requested changes
The changes look good, I only have a few questions/suggestions.

2022-05-10 19:31 UTC, valaparthvi commented on pkg/odo/cli/describe/component.go
> +	}
Perhaps you can reintroduce [Describef](https://github.com/redhat-developer/odo/blob/v2/pkg/log/status.go#L338) with this PR.

```suggestion
	if cmp.DevfileData != nil {
		log.Describef("Name: ", cmp.DevfileData.Devfile.GetMetadata().Name)
		log.Describef("Display Name: ", cmp.DevfileData.Devfile.GetMetadata().DisplayName)
		log.Describef("Project Type: ", cmp.DevfileData.Devfile.GetMetadata().ProjectType)
		log.Describef("Language: ", cmp.DevfileData.Devfile.GetMetadata().Language)
		log.Describef("Version: ", cmp.DevfileData.Devfile.GetMetadata().Version)
		log.Describef("Description: ", cmp.DevfileData.Devfile.GetMetadata().Description)
		log.Describef("Tags: ", strings.Join(cmp.DevfileData.Devfile.GetMetadata().Tags, ", "))
		fmt.Println()
	}

	log.Describef("Running in: ", cmp.RunningIn.String())
	fmt.Println()

	if len(cmp.DevForwardedPorts) > 0 {
		log.Info("Forwarded ports:")
		for _, port := range cmp.DevForwardedPorts {
			log.Printf("%s:%d -> %s:%d", port.LocalAddress, port.LocalPort, port.ContainerName, port.ContainerPort)
		}
		fmt.Println()
	}

	log.Info("Supported odo features:")
	if cmp.DevfileData != nil && cmp.DevfileData.SupportedOdoFeatures != nil {
		log.Printf("Dev: %v", cmp.DevfileData.SupportedOdoFeatures.Dev)
		log.Printf("Deploy: %v", cmp.DevfileData.SupportedOdoFeatures.Deploy)
		log.Printf("Debug: %v", cmp.DevfileData.SupportedOdoFeatures.Debug)
	} else {
		log.Printf("Dev: Unknown")
		log.Printf("Deploy: Unknown")
		log.Printf("Debug: Unknown")
	}
```

<details>
<summary>**Outcome:**</summary>

![Screenshot from 2022-05-11 00-45-09](https://user-images.githubusercontent.com/11015077/167705686-bd0964fb-22e8-40c2-a9cc-07f4ca31380b.png)
</details>

2022-05-10 19:31 UTC, valaparthvi commented on pkg/odo/cli/describe/component.go
> +		fmt.Printf("%s Unknown\n\n", title)
```suggestion
		log.Describef(title, " Unknown")
```

2022-05-10 19:31 UTC, valaparthvi commented on pkg/odo/cli/describe/component.go
> +	}
```suggestion
	log.Info(title)
	for _, container := range containers {
		log.Printf("%s", container.Name)
	}
```

2022-05-11 08:59 UTC, valaparthvi approved these changes
Thank you for working on those changes, Philippe!

2022-05-11 12:23 UTC, rm3l reviewed
LGTM, but I had a few small questions (might be enhancements for other PRs) :)

- In the "Running in" section, do we want to be more specific with the "Debug" Dev mode? Because the command displays "Dev" no matter if I run `odo dev` or `odo dev --debug`.
I found it a bit strange given that the "Supported odo features" section clearly lists "Debug" as a possible feature supported, but this is currently not listed in "Running in" when running in this mode.

- Also, I understood that the "Supported odo features" information is determined from the current Devfile and currently displays "Unknown" when running with `--name`. When running with the `--name` flag, if a mode (`Dev` and/or `Deploy`) is detected and listed in the "Running in" section, it means that this feature is supported by `odo`, no?
```
❯ odo describe component --name my-app             
Name: my-app
Display Name: Unknown
Project Type: quarkus
Language: Unknown
Version: Unknown
Description: Unknown
Tags: 

Running in: Dev, Deploy

Supported odo features:
 •  Dev: Unknown
 •  Deploy: Unknown
 •  Debug: Unknown
```

2022-05-11 12:32 UTC, feloy commented
> LGTM, but I had a few small questions (might be enhancements for other PRs) :)
> 
> * In the "Running in" section, do we want to be more specific with the "Debug" Dev mode? Because the command displays "Dev" no matter if I run `odo dev` or `odo dev --debug`.
>   I found it a bit strange given that the "Supported odo features" section clearly lists "Debug" as a possible feature supported, but this is currently not listed in "Running in" when running in this mode.



> * Also, I understood that the "Supported odo features" information is determined from the current Devfile and currently displays "Unknown" when running with `--name`. When running with the `--name` flag, if a mode (`Dev` and/or `Deploy`) is detected and listed in the "Running in" section, it means that this feature is supported by `odo`, no?

I think the odo supported features is mostly used to indicate that we can run the command "odo dev/deploy". Even if the component has been deployed, doesn't mean we can run it now (in this case, we couldn't, because we don't have the Devfile)

2022-05-11 13:18 UTC, rm3l commented
> > * Also, I understood that the "Supported odo features" information is determined from the current Devfile and currently displays "Unknown" when running with `--name`. When running with the `--name` flag, if a mode (`Dev` and/or `Deploy`) is detected and listed in the "Running in" section, it means that this feature is supported by `odo`, no?
> 
> I think the odo supported features are mostly intended to indicate that we can run the command "odo dev/deploy". Even if the component has been deployed, doesn't mean we can run it now (in this case, we couldn't, because we don't have the Devfile)

Okay, I see. Thanks.

2022-05-12 09:10 UTC, valaparthvi commented
/lgtm

2022-05-12 09:23 UTC, rm3l commented
/approve

2022-05-12 10:30 UTC, merged