odo add binding documentation
redhat-developer/odo pull request #5730
Opened 2022-05-11 05:18 UTC by valaparthvi

Signed-off-by: Parthvi Vala <pvala@redhat.com>

**What type of PR is this:**

/kind documentation

**What does this PR do / why we need it:**
This PR adds documentation for `odo add binding`.

**Which issue(s) this PR fixes:**

Fixes part of #5627 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-05-11 05:18 UTC, valaparthvi commented
/hold
Until #5641 is merged.

2022-05-11 06:42 UTC, feloy requested changes

2022-05-11 06:42 UTC, feloy commented on docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
> +The above formats are helpful when multiple services with the same name exists on the cluster.
```suggestion
The above formats are helpful when multiple services with the same name exist on the cluster.
```

2022-05-11 06:42 UTC, feloy commented on docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
> +odo add binding --service myservice.Redis.redis.redis.opstreelab.in --name myRedisService
```suggestion
```

2022-05-11 06:42 UTC, feloy commented on docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
> +odo add binding --service myservice.Redis --name myRedisService
```suggestion
```

2022-05-11 13:03 UTC, feloy commented on docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
> +odo add binding --service myservice.Redis.redis.redis.opstreelab.in --name myRedisService
Oh sorry, I didn't see the difference between the two lines. 
Perhaps you can highlight the difference in some way, with some "note the different notations for the service name"?

2022-05-11 13:12 UTC, feloy approved these changes

2022-05-12 13:06 UTC, valaparthvi commented
/hold cancel

2022-05-12 17:03 UTC, feloy commented
/approve

2022-05-12 20:35 UTC, merged