odo registry -o json
redhat-developer/odo pull request #5739
Opened 2022-05-12 16:56 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5644

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-05-13 14:14 UTC, rm3l requested changes
Overall LGTM. I added few comments however ;)

2022-05-13 14:14 UTC, rm3l commented on docs/website/versioned_docs/version-3.0.0/command-reference/registry.md
> +* `--filter <term>` to list the Devfile for which the term is found in the devfile name or description
Can you also update the CLI Help message of this command? Currently, it says that the filter is based on the name of the component:

```
❯ odo help registry        
List all components from the Devfile registry

Usage:
  odo registry [flags]

Flags:
      --details                   Show details of each component
      --devfile string            Only the specific Devfile component
      --devfile-registry string   Only show components from the specific Devfile registry
      --filter string             Filter based on the name of the component
```

2022-05-13 14:14 UTC, rm3l commented on docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
> +The `componentInDevfile` field gives the name of components present in the `components` list that are defined in the local Devfile, or is empty if no local Devfile is present.
I guess `components` should not be plural here, as we are now returning at most one name.

```suggestion
The `componentInDevfile` field gives the name of the component present in the `components` list and defined in the local Devfile, or is empty if no local Devfile is present.
```

2022-05-13 14:21 UTC, rm3l reviewed
Another small improvement about the error message if a wrong registry is specified.

Wouldn't it be better, from the user perspective, to report that the registry was not found in the registry list, rather than saying `no deployable components found`?

```
❯ odo registry --devfile java-maven --devfile-registry fake-registry -o json
{
        "message": "no deployable components found"
}
```

2022-05-13 14:33 UTC, feloy commented on pkg/api/registry.go
> +}
I don't think anymore this information is necessary. Removing it from the Issue

2022-05-13 15:08 UTC, rm3l approved these changes

2022-05-16 08:08 UTC, rm3l commented
/approve

2022-05-16 09:25 UTC, rm3l approved these changes

2022-05-16 09:25 UTC, rm3l commented on tests/integration/devfile/cmd_devfile_init_test.go
> +				helper.JsonPathContentIs(stdout, "devfileData.devfile.metadata.name", compName)
I was about to check why tests were not passing, but you were too faster :-P 👍🏿

2022-05-16 10:31 UTC, feloy commented
```
• Failure [7.628 seconds]
create/delete/list/get/set namespace tests
/go/src/github.com/redhat-developer/odo/tests/integration/cmd_namespace_test.go:14
  when using the alias namespace to delete a namespace
  /go/src/github.com/redhat-developer/odo/tests/integration/cmd_namespace_test.go:52
    should successfully delete the namespace using the force flag and waiting [It]
    /go/src/github.com/redhat-developer/odo/tests/integration/cmd_namespace_test.go:81
```

/test v4.10-integration-e2e

2022-05-16 11:44 UTC, feloy commented
Flaky tests on non related tests
Tests pass on IBM Cloud

/override ci/prow/v4.10-integration-e2e

2022-05-16 11:45 UTC, merged