Update preference view to show list of devfile registries
redhat-developer/odo pull request #5850
Opened 2022-06-21 09:52 UTC by valaparthvi

**What type of PR is this:**
/kind feature

**What does this PR do / why we need it:**
This PR moves `odo preference registry list` to `odo preference view`.
**Which issue(s) this PR fixes:**

Fixes part of #5535 

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
Example 1-
```sh
$ odo preference view

Preference parameters:
 PARAMETER           VALUE          
 ConsentTelemetry    true           
 Ephemeral                          
 PushTimeout                        
 RegistryCacheTime                  
 Timeout             5              
 UpdateNotification  true (default) 

Devfile registries:
 NAME                    URL                          SECURE 
 DefaultDevfileRegistry  https://registry.devfile.io  No   
```

Example 2 - 
```sh
$ odo preference view
Preference parameters:
 PARAMETER           VALUE          
 ConsentTelemetry    true           
 Ephemeral                          
 PushTimeout                        
 RegistryCacheTime                  
 Timeout             5              
 UpdateNotification  true (default) 

Devfile registries:
 ⚠  No devfile registries added to the configuration. Refer `odo preference registry add -h` to add one
```

2022-06-21 14:33 UTC, valaparthvi commented
/override ci/prow/unit
/override ci/prow/v4.10-integration-e2e

2022-06-22 08:00 UTC, rm3l requested changes

2022-06-22 09:02 UTC, valaparthvi commented on pkg/odo/cli/preference/view.go
> +	preferenceT := table.NewWriter()
Oh yes, definitely. I didn't realize that was in.

2022-06-22 12:23 UTC, valaparthvi commented
/override ci/prow/unit
/override ci/prow/v4.10-integration-e2e

2022-06-23 10:19 UTC, feloy commented
/approve

2022-06-24 05:22 UTC, valaparthvi commented
/override ci/prow/v4.10-integration-e2e

2022-06-24 11:59 UTC, rm3l requested changes
Just one last small change ^^

2022-06-24 11:59 UTC, rm3l commented on pkg/odo/cli/preference/view.go
> +		log.Warning("No devfile registries added to the configuration. Refer `odo preference registry add -h` to add one")
```suggestion
		log.Warning("No devfile registries added to the configuration. Refer to `odo preference registry add -h` to add one")
```

2022-06-24 14:32 UTC, rm3l approved these changes

2022-06-27 06:39 UTC, valaparthvi commented
/override ci/prow/v4.10-integration-e2e
/override ci/prow/unit

2022-06-27 07:35 UTC, rm3l approved these changes

2022-06-27 07:37 UTC, merged