Fixes terminal completion command for odo
redhat-developer/odo pull request #5856
Opened 2022-06-21 19:39 UTC by cdrage

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**

This PR:
* Changes the command `odo utils terminal` to `odo completion` similar
  to kubectl.
* Re-enables / fixes the terminal completion command support for bash,
  zsh, fish and powershelll
* Updates Cobra to 1.13 to enable support for autocompleting descriptive
  commands.

**Which issue(s) this PR fixes:**

Fixes #5536

**How to test changes / Special notes to the reviewer:**

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2022-06-21 19:45 UTC, cdrage commented
If people can please test please do!

The instructions are at `odo completion --help` for bash, zsh, powershell and fish.

2022-06-22 13:05 UTC, valaparthvi commented
@cdrage, do you think you can add a documentation for this command?

2022-06-22 13:07 UTC, rm3l commented
@cdrage I reproduced what I was mentioning during the Standup call. Unlike the other additional flags, `-o` does not seem to be listed in the completion list. Don't know if that is the expected behavior with this flag.
I am using zsh, FYI.

Example with `odo analyze`:
```
❯ odo analyze -<TAB>
--kubeconfig      -- Paths to a kubeconfig. Only required if out-of-cluster.                                                                                                                                                                                                   
--v           -v  -- number for the log level verbosity. Level varies from 0 to 9 (default 0).                                                                                                                                                                                 
--vmodule         -- comma-separated list of pattern=N settings for file-filtered logging
```

And here is the help output of `odo analyze`, which mentions the `-o` option.:
```
❯ odo analyze --help 
Detect devfile to use based on files present in current directory

Usage:
  odo analyze [flags]

Flags:
  -h, --help   Help for analyze

Additional Flags:
      --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
  -o, --o string             Specify output format, supported format: json
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
```

Same behavior with `odo describe component` or `odo describe binding`.

2022-06-22 13:09 UTC, valaparthvi requested changes

2022-06-22 13:09 UTC, valaparthvi commented on pkg/odo/cli/completion/completion.go
> +	%[1]s completion powershell >> $PROFILE
```suggestion
	%[1]s powershell | Out-String | Invoke-Expression

	## Load persistently
	%[1]s powershell >> $PROFILE
```

2022-06-22 13:19 UTC, cdrage commented
> @cdrage I reproduced what I was mentioning during the Standup call. Unlike the other additional flags, `-o` does not seem to be listed in the completion list. Don't know if that is the expected behavior with this flag. I am using zsh, FYI.
> 
> Example with `odo analyze`:
> 
> ```
> ❯ odo analyze -<TAB>
> --kubeconfig      -- Paths to a kubeconfig. Only required if out-of-cluster.                                                                                                                                                                                                   
> --v           -v  -- number for the log level verbosity. Level varies from 0 to 9 (default 0).                                                                                                                                                                                 
> --vmodule         -- comma-separated list of pattern=N settings for file-filtered logging
> ```
> 
> And here is the help output of `odo analyze`, which mentions the `-o` option.:
> 
> ```
> ❯ odo analyze --help 
> Detect devfile to use based on files present in current directory
> 
> Usage:
>   odo analyze [flags]
> 
> Flags:
>   -h, --help   Help for analyze
> 
> Additional Flags:
>       --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
>   -o, --o string             Specify output format, supported format: json
>   -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
>       --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
> ```
> 
> Same behavior with `odo describe component` or `odo describe binding`.

Ah! That's a bug, I'll find it. Thank you. Odd that it's only `-o` doing it.

2022-06-22 13:26 UTC, valaparthvi requested changes

2022-06-22 13:53 UTC, cdrage commented
/retest

2022-06-24 06:24 UTC, feloy commented on pkg/odo/cli/cli.go
> -	_ = pflag.CommandLine.MarkHidden("o")
By removing this, the option now appears in all commands, event if they do not support it.

2022-06-27 15:20 UTC, cdrage commented
@feloy @rm3l 

Fixed!

Basically... I've unhidden the -o flag, but I've modified the help usage page to hide it if it's not supported.

Essentially, we cannot "unhide" and "hide" flags programatically within Cobra in order to generate the correct bash completion.

Unfortunately, with the way that completion is handled within cobra, it'll still show for each command.

```sh
go/src/odo  fix-utils ✗                                                                                                                                                                                                                                                                                                                                         3d21h ⚑
▶ odo deploy --o json
 ✗  Machine readable output is not yet implemented for this command
```

Ex. For when trying to run it.

I suggest that we still merge this in, and create an issue upstream (Cobra) as well as an issue within our repo with a WONTFIX until it's fixed upstream.

2022-06-29 13:14 UTC, feloy commented
You will need to fix these "validate" errors:

```
pkg/odo/cli/completion/completion.go:72:33: Error return value of `(*github.com/spf13/cobra.Command).GenBashCompletion` is not checked (errcheck)
				cmd.Root().GenBashCompletion(os.Stdout)
				                            ^
pkg/odo/cli/completion/completion.go:79:14: Error return value of `out.Write` is not checked (errcheck)
				out.Write([]byte(zsh))
				         ^
pkg/odo/cli/completion/completion.go:80:32: Error return value of `(*github.com/spf13/cobra.Command).GenZshCompletion` is not checked (errcheck)
				cmd.Root().GenZshCompletion(out)
				                           ^
pkg/odo/cli/completion/completion.go:82:33: Error return value of `(*github.com/spf13/cobra.Command).GenFishCompletion` is not checked (errcheck)
				cmd.Root().GenFishCompletion(os.Stdout, true)
				                            ^
pkg/odo/cli/completion/completion.go:84:47: Error return value of `(*github.com/spf13/cobra.Command).GenPowerShellCompletionWithDesc` is not checked (errcheck)
				cmd.Root().GenPowerShellCompletionWithDesc(os.Stdout)
```

2022-06-30 13:07 UTC, feloy approved these changes

2022-06-30 13:07 UTC, cdrage commented
Ready for review 👍 @rm3l @valaparthvi

2022-06-30 14:06 UTC, rm3l approved these changes
Tested with both ZSH and Bash, and completion works great 🎉

One side note: we could have added this to the documentation (command reference and/or somewhere in the installation guide). For now, this seems hidden as a feature.

/approve

2022-07-01 06:56 UTC, feloy commented
/override ci/prow/unit
/override ci/prow/v4.10-integration-e2e

2022-07-01 07:27 UTC, feloy commented
/override ci/prow/unit
/override ci/prow/v4.10-integration-e2e

2022-07-01 07:29 UTC, merged

2022-07-05 12:12 UTC, cdrage commented
> 

You're right, I'll add a doc for that!