download golangci-lint binary with test script
redhat-developer/odo pull request #5934
Opened 2022-07-08 12:41 UTC by anandrkskd

Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**

/area testing

**What does this PR do / why we need it:**

Removing golangci-lint from the script, as the installation is added as [pre step](https://github.com/anandrkskd/release/blob/0692f2611817db9766dd338317b5627e4c4b52cf/ci-operator/config/redhat-developer/odo/redhat-developer-odo-main.yaml#L14) in unit test set on prow, it downloads the binary directly for the test.

**Which issue(s) this PR fixes:**

Fixes [#5879](https://github.com/redhat-developer/odo/issues/5879)

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-07-12 19:55 UTC, anandrkskd commented
/retest

2022-07-13 15:54 UTC, rm3l requested changes

2022-07-13 15:54 UTC, rm3l commented on scripts/openshiftci-presubmit-unittests.sh
> +chmod +x $(go env GOPATH)/bin/golangci-lint
Wouldn't it make more sense to change the `goget-tools` target instead to install `golangci-lint` via `wget` + `tar`? This way, we would have a single place to look at if we have to change the version of `golangci-lint` in the future. And we would be sure to have the exact version locally and in all our test platforms.

2022-07-13 15:54 UTC, rm3l commented on scripts/openshiftci-presubmit-unittests.sh
> +chmod +x $(go env GOPATH)/bin/golangci-lint
Also, I think it would be nice to extract the version of `golangci-lint` as a local variable, so it can be easily updated in the future.

2022-07-15 10:38 UTC, dharmit commented
/approve

@rm3l could you PTAL for the LGTM flag?

2022-07-15 11:51 UTC, rm3l requested changes
Added a few comments.

I was also wondering: have we tried any of the other installation methods recommended in the [installation docs](https://golangci-lint.run/usage/install/)? Like:
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.37.0
```

This might be slower than binary installation, but maybe this would solve the issue with determining the best binary to use without using their `install.sh` script.

2022-07-15 11:51 UTC, rm3l commented on scripts/openshiftci-presubmit-unittests.sh
> +make goget-tools
This extra space may not be needed anymore, to reduce the scope of changes.

2022-07-15 11:57 UTC, rm3l commented
> Added a few comments.
> 
> I was also wondering: have we tried any of the other installation methods recommended in the [installation docs](https://golangci-lint.run/usage/install/)? Like:
> 
> ```
> go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.37.0
> ```
> 
> This might be slower than binary installation, but maybe this would solve the issue of determining the best binary to use without using their `install.sh` script.

We could even use this `go install` way as a fallback mechanism if the `install.sh` fails, e.g.:
```shell
(curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin v1.37.0) || \
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.37.0
```

2022-07-15 12:03 UTC, anandrkskd commented
I can give a try but, I am not sure if using go install is a good step as the doc states it `we've encountered a lot of issues with Go modules hashes.` 

I will use the command you suggested.

2022-07-15 12:20 UTC, rm3l commented
> I can give a try but, I am not sure if using go install is a good step as the doc states it `we've encountered a lot of issues with Go modules hashes.`
> 
Ah, I see. In this case, I think it makes even more sense to use this as a last resort. 

> I will use the command you suggested.

Great - let's see how it goes now.. BTW, I think we should also use the tagged version of the `install.sh` script, so we don't have any future surprises in the future. So the command should be this instead, IMO. Extracting the version as a local variable would be even better.

```shell
(curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.37.0/install.sh | sh -s -- -b $(shell go env GOPATH)/bin v1.37.0) || \
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.37.0
```

2022-07-15 14:59 UTC, rm3l commented on scripts/openshiftci-presubmit-unittests.sh
> +make goget-tools
LGTM, but could you also remove the extra space added here?

2022-07-18 07:16 UTC, rm3l approved these changes

2022-07-18 10:56 UTC, valaparthvi commented
/override OpenShift Integration tests/OpenShift Integration tests

Test failure is unrelated.

2022-07-18 11:30 UTC, anandrkskd commented
/retest

2022-07-18 15:09 UTC, merged