Refactor color througout interactive mode and dev
redhat-developer/odo pull request #5963
Opened 2022-07-21 18:38 UTC by cdrage

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**

This PR fixes the following:
- Updates the interactive mode so it's better looking when outputting
  configuration so it's similar to the rest of the output:

```sh
? Is this correct? Yes
 ✓  Downloading devfile "nodejs" from registry "DefaultDevfileRegistry" [1s]

↪ Container Configuration "runtime":
  OPEN PORTS:
    - 3000
  ENVIRONMENT VARIABLES:

? Select container for which you want to change configuration? runtime
? What configuration do you want change? Delete port "3000"
? What configuration do you want change? NOTHING - configuration is correct

↪ Container Configuration "runtime":
  OPEN PORTS:
  ENVIRONMENT VARIABLES:

? Select container for which you want to change configuration?  [Use arrows to move, type to filter]
  runtime
> NONE - configuration is correct
```

- Removes issue of fgGreen not appearing correctly because of direct use
  of `color` instead of log/status.go. This is due to color not
  detecting if the terminal supports the color, which is done in
  `log/status.go` instead.

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/5843

**How to test changes / Special notes to the reviewer:**

2022-07-22 10:34 UTC, dharmit requested changes

2022-07-22 10:34 UTC, dharmit commented on pkg/init/backend/interactive.go
> +	fmt.Println()
Please don't use `fmt.Printf` or `fmt.Println` in the business layer. It should ideally be used only in CLI layer. Use `fmt.Fprintf` with stdout as `io.Writer`.

2022-07-23 00:04 UTC, cdrage commented
Thanks! Updated @dharmit

2022-07-23 07:21 UTC, dharmit commented
/lgtm

2022-07-25 15:58 UTC, rm3l reviewed
/approve

2022-07-26 06:04 UTC, valaparthvi commented
/override ci/prow/v4.10-integration-e2e

2022-07-26 12:38 UTC, cdrage commented
Re-added

/lgtm

Because I forgot to sign the commit

2022-07-26 16:08 UTC, rm3l commented
/override ci/prow/v4.10-integration-e2e

Tests passing in IBM Cloud.

2022-07-26 16:12 UTC, merged