Add spinner ending for running command
redhat-developer/odo pull request #5964
Opened 2022-07-21 18:50 UTC by cdrage

**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

When running `odo dev`, it will never show that the command has
completed.

```sh
 ✓  Building your application in container on cluster (command: install) [3s]
 •  Executing the application (command: run)  ...
 -  Forwarding from 127.0.0.1:40001 -> 3000
```

`spinner.End` hadn't been added so it never shows at it ending.

This PR fixes that:

```sh
 ✓  Building your application in container on cluster (command: install) [3s]
 •  Executing the application (command: run)  ...
 ✓  Executing the application (command: run) [5s]
 ```

**Which issue(s) this PR fixes:**

N/A

**How to test changes / Special notes to the reviewer:**

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2022-07-22 10:38 UTC, rm3l requested changes
> When running `odo dev`, it will never show that the command has completed.
> 
> ```shell
>  ✓  Building your application in container on cluster (command: install) [3s]
>  •  Executing the application (command: run)  ...
>  -  Forwarding from 127.0.0.1:40001 -> 3000
> ```
> 
> `spinner.End` hadn't been added so it never shows at it ending.
> 
> This PR fixes that:
> 
> ```shell
>  ✓  Building your application in container on cluster (command: install) [3s]
>  •  Executing the application (command: run)  ...
>  ✓  Executing the application (command: run) [5s]
> ```
> 
@cdrage With the removal of Supervisord, `odo dev` now executes the `run` or `debug` command in a separate goroutine. So to me, we cannot know for sure when the command is done (until the corresponding goroutine reports so). This is why we used a spinner that does not end.
So adding a spinner that ends here can be a bit misleading to the users, no?

Let's say the command exits a few seconds/minutes later (simulated by the command below in my Devfile):

```yaml
- exec:
    commandLine: 'sleep 10 && echo Exiting... && exit 1'
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: $PROJECT_SOURCE
  id: run
```

With the changes in this PR, the spinner has already ended, so it will never be updated again, and the user would never know that the command failed:
```
❯ odo dev      
  __
 /  \__     Developing using the my-nodesjs-with-k8s-uri-with-var Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.0.0-beta2
 \__/

↪ Deploying to the cluster in developer mode
 ✓  Waiting for Kubernetes resources [6s]
 ✓  Syncing files into the container [151ms]
 ✓  Building your application in container on cluster (command: install) [4s]
 •  Executing the application (command: run)  ...
 ✓  Executing the application (command: run) [5s]
 - Forwarding from 127.0.0.1:40003 -> 8080

Your application is now running on the cluster

Watching for changes in the current directory /home/asoro/work/tmp/5451-deploy-k8s-uri-var-substitution
Press Ctrl+c to exit `odo dev` and delete resources from the cluster
```

Before, users had such information at the end:
```
❯ odo dev
  __
 /  \__     Developing using the my-nodesjs-with-k8s-uri-with-var Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.0.0-beta2
 \__/

↪ Deploying to the cluster in developer mode
 ✓  Waiting for Kubernetes resources [8s]
 ✓  Syncing files into the container [160ms]
 ✓  Building your application in container on cluster (command: install) [5s]
 •  Executing the application (command: run)  ...
 - Forwarding from 127.0.0.1:40003 -> 8080

Your application is now running on the cluster

Watching for changes in the current directory /home/asoro/work/tmp/5451-deploy-k8s-uri-var-substitution
Press Ctrl+c to exit `odo dev` and delete resources from the cluster

 ✗  Executing the application (command: run) [10s]

```

2022-07-23 00:00 UTC, cdrage commented
> •  Executing the application (command: run)  ...

Ah, I get your point.

The problem is.. it looks really out of place with the spinner.

We should remove the spinner entirely and just have a prompt saying that the command would be running in the background? I don't like how it's out of place with all the other stuff in the workflow when running `odo dev`. 

We should just have it as:

```sh
 ↪ Deploying to the cluster in developer mode
 ✓  Waiting for Kubernetes resources [8s]
 ✓  Syncing files into the container [160ms]
 ✓  Building your application in container on cluster (command: install) [5s]
 ✓  Executing the application (command: run) in the background
 - Forwarding from 127.0.0.1:40003 -> 8080
 ```

Instead of the spinner.

What do you think?

2022-07-25 08:29 UTC, rm3l commented
> > •  Executing the application (command: run)  ...
> 
> Ah, I get your point.
> 
> The problem is.. it looks really out of place with the spinner.
> 
> We should remove the spinner entirely and just have a prompt saying that the command would be running in the background? I don't like how it's out of place with all the other stuff in the workflow when running `odo dev`.
> 
> We should just have it as:
> 
> ```shell
>  ↪ Deploying to the cluster in developer mode
>  ✓  Waiting for Kubernetes resources [8s]
>  ✓  Syncing files into the container [160ms]
>  ✓  Building your application in container on cluster (command: install) [5s]
>  ✓  Executing the application (command: run) in the background
>  - Forwarding from 127.0.0.1:40003 -> 8080
> ```
> 
> Instead of the spinner.
> 
> What do you think?

That would be better indeed, as long as we are able to report the command status later (as shown in my previous example), if the command exits at any later point in time (either successfully or not).

2022-07-26 23:43 UTC, cdrage commented
Closing this in favour of https://github.com/redhat-developer/odo/pull/5972

2022-07-27 00:14 UTC, closed without merging