Add extra output when init project using odo dev
redhat-developer/odo pull request #6127
Opened 2022-09-15 19:29 UTC by cdrage

Add extra output when init project using odo dev

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**

Updates the messaging when you run `odo dev` and there is no
`devfile.yaml` available. Outputs more information that makes it similar
to running `odo dev` or `odo init`

**Which issue(s) this PR fixes:**

Fixes https://github.com/redhat-developer/odo/issues/5679

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

2022-09-16 08:42 UTC, rm3l requested changes
I think we currently have the same kind of issue when running `odo deploy` in a dir with no devfile.yaml:
```
❯ odo deploy                                                                                
The current directory already contains source code. odo will try to autodetect the language and project type in order to select the best suited Devfile for your project.
Based on the files in the current directory odo detected
Language: go
Project type: go
The devfile "go" from the registry "DefaultDevfileRegistry" will be downloaded.
? Is this correct? (Y/n)
```

To be consistent, can you do the same thing for `odo deploy` as well?

2022-09-16 08:42 UTC, rm3l commented on pkg/odo/cli/messages/messages.go
> +const InitializeExistingComponent = "Dev mode ran, but no Devfile was found. Initializing a Devfile in the current directory"
This constant is not used and could be removed.

2022-09-16 08:47 UTC, rm3l commented
Also, I think there are some tests (introduced in #5556)  that would need to be fixed/rewritten: they were testing that we had the previous messages displayed first in the output.

2022-09-16 12:44 UTC, cdrage commented
> I think we currently have the same kind of issue when running `odo deploy` in a dir with no devfile.yaml:
> 
> ```
> ❯ odo deploy                                                                                
> The current directory already contains source code. odo will try to autodetect the language and project type in order to select the best suited Devfile for your project.
> Based on the files in the current directory odo detected
> Language: go
> Project type: go
> The devfile "go" from the registry "DefaultDevfileRegistry" will be downloaded.
> ? Is this correct? (Y/n)
> ```
> 
> To be consistent, can you do the same thing for `odo deploy` as well?

Good point, I'll do the same for `odo deploy`

2022-09-20 20:22 UTC, cdrage commented
/retest

2022-09-21 18:22 UTC, cdrage commented
/retest

2022-09-22 03:52 UTC, valaparthvi requested changes
While you're at this, can we make an additional change to `odo dev` and `odo deploy` messages?
When there is a devfile present and you run either of the commands, it says "Developing using the devfile-nodejs-deploy Devfile", can we double-quote the devfile name? I always find it very confusing to determine the component/devfile name when these commands are run.

2022-09-22 03:52 UTC, valaparthvi commented on tests/integration/interactive_dev_test.go
> +			Expect(lines[1]).To(ContainSubstring("Dev mode ran, but no Devfile was found. Initializing a Devfile in the current directory"))
`odo init` says "Initializing new component" when downloading devfile, while `odo dev` and `odo deploy` say "Initializing a Devfile". Can we make these messages more consistent?

2022-09-22 14:35 UTC, cdrage commented
Thanks @valaparthvi I've updated it based on your review and also made changes to the Devfile output / added double quotes.

2022-09-23 08:22 UTC, valaparthvi commented
/lgtm
Thanks for patiently working on all the changes, Charlie. :)

2022-09-23 08:23 UTC, valaparthvi commented
/retest

2022-09-23 11:59 UTC, rm3l reviewed
Thanks for the changes.

/approve

2022-09-23 12:36 UTC, feloy commented
/override ci/prow/v4.11-integration-e2e
Pass on IBM Cloud

2022-09-23 13:23 UTC, merged