Note regarding image visibility for odo deploy
redhat-developer/odo pull request #6191
Opened 2022-10-04 11:31 UTC by dharmit

Signed-off-by: Dharmit Shah <shahdharmit@gmail.com>

**What type of PR is this:**
/kind documentation

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**
Fixes #6107 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-10-04 14:07 UTC, rm3l reviewed
LGTM, but can you also include this note somewhere in the [command reference page for `odo deploy`](https://deploy-preview-6191--odo-docusaurus-preview.netlify.app/docs/command-reference/deploy)? Thanks.

2022-10-05 13:01 UTC, cdrage requested changes

2022-10-05 13:01 UTC, cdrage commented on docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
> +Depending upon the container registry which you specified in the `devfile.yaml`, the access for container image
```suggestion
Depending upon the container registry specified in the `devfile.yaml`, the access for container image
```

2022-10-05 13:01 UTC, cdrage commented on docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
> +pushed by `odo deploy` might be private by default, e.g., images pushed to [Quay.io](https://quay.io). Change the
```suggestion
pushed by `odo deploy` may be private by default. For example: images pushed to [Quay.io](https://quay.io). Change the
```

2022-10-05 13:01 UTC, cdrage commented on docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
> +image visibility appropriately to be able to run `odo deploy` successfully.
```suggestion
image visibility appropriately in order to run `odo deploy` successfully.
```

2022-10-06 06:42 UTC, dharmit commented
> LGTM, but can you also include this note somewhere in the [command reference page for `odo deploy`](https://deploy-preview-6191--odo-docusaurus-preview.netlify.app/docs/command-reference/deploy)? Thanks.

Added.

2022-10-06 07:29 UTC, rm3l approved these changes

2022-10-06 10:32 UTC, feloy commented
/approve

2022-10-06 10:36 UTC, merged