Make exec package agnostic of platform
redhat-developer/odo pull request #6217
Opened 2022-10-12 14:49 UTC by feloy

**What type of PR is this:**

/kind cleanup

**What does this PR do / why we need it:**

This package makes the exec package, and thus the sync package using it, agnostic of the platform. 
 The platform is injected by the dependency injection system, depending on the `--run-on` flag.

**Which issue(s) this PR fixes:**

Fixes #6160 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-10-13 10:58 UTC, valaparthvi requested changes

2022-10-13 10:58 UTC, valaparthvi commented on pkg/sync/copy.go
> +	return nil
```suggestion
	}
	return err
```

2022-10-13 10:58 UTC, valaparthvi commented on pkg/sync/sync.go
>  // SyncClient is a Kubernetes implementationn for sync
```suggestion
// SyncClient is a Kubernetes implementation for sync
```

Or maybe something more appropriate.

2022-10-18 07:38 UTC, valaparthvi approved these changes

2022-10-18 07:40 UTC, valaparthvi commented
/retest

2022-10-19 09:52 UTC, rm3l reviewed
/approve

2022-10-21 08:19 UTC, valaparthvi approved these changes

2022-10-21 08:25 UTC, valaparthvi commented
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests
/override OpenShift-Integration-tests/OpenShift-Integration-tests
/override ci/prow/v4.11-integration-e2e
Overriding the tests. All point to the same failure.
```
Summarizing 2 Failures:
  [FAIL] E2E Test starting with non-empty Directory [It] should verify developer workflow from non-empty Directory
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_interactive.go:111
  [FAIL] E2E Test starting with empty Directory [It] should verify developer workflow from empty Directory
  /go/src/github.com/redhat-developer/odo/tests/helper/helper_generic.go:76

Ran 6 of 6 Specs in 162.545 seconds
FAIL! -- 4 Passed | 2 Failed | 0 Pending | 0 Skipped
```

@feloy I think it's alright to merge this PR given the errors. But I am going to put this on hold, in case you'd like to wait until #6243 goes in. Feel free to remove the hold if you want it to go in right away.

/hold

2022-10-21 08:39 UTC, feloy commented
/override NoCluster-Integration-tests/NoCluster-Integration-tests
Not applicable

2022-10-21 08:50 UTC, merged