display equivalent odo init command for odo init interactive
redhat-developer/odo pull request #6265
Opened 2022-10-27 14:27 UTC by anandrkskd

Signed-off-by: anandrkskd <anandrkskd@gmail.com>

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #5465 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
```
run `odo init` in interactive mode
odo init
```

2022-10-28 09:05 UTC, feloy requested changes

2022-10-28 09:05 UTC, feloy commented on pkg/odo/cli/init/init.go
> +	}
I would separate the build of the comamnd string from the rest of the message.

Also, the condition of len(o.flags) could be placed n a better place.

I think you could instead write something like:

```
if len(o.flags) == 0 {
  automateCommad := fmt.Sprintf(odo init --name %s --devfile %s --devfile-registry %s", ...)
  if starterInfo != nil {
    automateCommand = fmt.Sprintf("%s --starter %s", automateCommad, starterInfo.Name
  }
  log.Infof("\nPort configuration using flag is currently not supported  \n\nYou can automate this command by executing:\n   %s\n", automateCommad)
}

2022-10-28 09:05 UTC, feloy commented on pkg/odo/cli/init/init.go
>  // run downloads the devfile and starter project and returns the content and the path of the devfile
Please adapt the documentation to add the new returned values

2022-11-03 14:16 UTC, feloy commented
@anandrkskd could you please rebase this PR?
e2e tests fail on some issue fixed by a PR merged recently

2022-11-03 14:21 UTC, anandrkskd commented
Thanks Philippe, rebased the PR.

2022-11-03 15:14 UTC, feloy commented
/approve

2022-11-03 19:34 UTC, feloy commented
/lgtm

2022-11-03 19:38 UTC, merged