More tests without cluster
redhat-developer/odo pull request #6303
Opened 2022-11-10 13:50 UTC by feloy

**What type of PR is this:**

/kind tests

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-11-17 10:52 UTC, feloy commented
@kadel I have made some changes on the behaviour of `odo describe component` and `odo list component`, to make them work without Kubernetes connection, and display only local Devfile info. Do you agree with these changes?

2022-11-18 10:52 UTC, rm3l requested changes
Thanks for this.

It works great when running `make test-integration-no-cluster` with no cluster:
```
$ KUBECONFIG=/dev/null make test-integration-no-cluster
...
Ran 95 of 410 Specs in 8.659 seconds
SUCCESS! -- 95 Passed | 0 Failed | 0 Pending | 315 Skipped

Ginkgo ran 1 suite in 14.421557831s
Test Suite Passed
``` 

But I noticed that when running `make test-integration-no-cluster` locally but with an active context, I'm seeing some tests not passing:
```
☸ kind-local-k8s-cluster in ~/w/p/odo on  more-tests-without-cluster [$] via 🐹 v1.18.8 on ☁️   
$ make test-integration-no-cluster
...
Summarizing 2 Failures:
  [FAIL] odo list with devfile devfile has missing metadata when projectType and language is missing [It] should show 'Not available' for 'Type' in odo list [nocluster]
  /home/asoro/work/projects/odo/tests/helper/helper_generic.go:273
  [FAIL] odo list with devfile devfile has missing metadata when projectType is missing [It] should show the language for 'Type' in odo list [nocluster]
  /home/asoro/work/projects/odo/tests/helper/helper_generic.go:273

Ran 95 of 410 Specs in 8.983 seconds
FAIL! -- 93 Passed | 2 Failed | 0 Pending | 315 Skipped

Ginkgo ran 1 suite in 15.02773153s

Test Suite Failed
exit status 1
make: *** [Makefile:197: test-integration-no-cluster] Error 1
```

I think the issue was specifically due to the change in behavior of `odo list`; I had some other unrelated components deployed in the cluster (in my current namespace) and `odo list` was listing them as well, which is the expected behavior:
```
    Running odo with args [odo list component] and odo env: []                                                                                                                                             [30/7131]
    [odo]  •  Listing components from namespace 'default'  ...                                                                                                                                                      
 ✓  Listing components from namespace 'default' [231ms]                                                                                                                                                             
    [odo]  NAME                      PROJECT TYPE   RUNNING IN  MANAGED                                                                                                                                             
    [odo]  my-java-maven-springboot  spring         Deploy      odo (v3.2.0)                                                                                                                                        
    [odo]  * aname                   Not available  None        Unknown                                                                                                                                             
    STEP: checking the JSON output 11/18/22 11:36:48.069                                                                                                                                                            
    Running odo with args [odo list component -o json] and odo env: []                                                                                                                                              
    [odo] {                                                                                                                                                                                                         
    [odo]       "componentInDevfile": "aname",                                                                                                                                                                      
    [odo]       "components": [                                                                                                                                                                                     
    [odo]               {                                                                                                                                                                                           
    [odo]                       "name": "my-java-maven-springboot",                                                                                                                                                 
    [odo]                       "managedBy": "odo",                                                                                                                                                                 
    [odo]                       "managedByVersion": "v3.2.0",                                                                                                                                                       
    [odo]                       "runningIn": {                                                                                                                                                                      
    [odo]                               "deploy": true,                                                                                                                                                             
    [odo]                               "dev": false                                                                                                                                                                
    [odo]                       },                                                                                                                                                                                  
    [odo]                       "projectType": "spring"                                                                                                                                                             
    [odo]               },                                                                                                                                                                                          
    [odo]               {                                                                                                                                                                                           
    [odo]                       "name": "aname",                                                                                                                                                                    
    [odo]                       "managedBy": "",                                                                                                                                                                    
    [odo]                       "managedByVersion": "",                                                                                                                                                             
    [odo]                       "runningIn": {                                                                                                                                                                      
    [odo]                               "deploy": false,                                                                                                                                                            
    [odo]                               "dev": false                                                                                                                                                                
    [odo]                       },                                                                                                                                                                                  
    [odo]                       "projectType": "Not available"                                                                                                                                                      
    [odo]               }                                  [...]

2022-11-18 14:27 UTC, feloy commented
> Thanks for this.
> 
> It works great when running `make test-integration-no-cluster` with no cluster:
> 
> [...]
>
> But I noticed that when running `make test-integration-no-cluster` locally but with an active context, I'm seeing some tests not passing:
>
> [...]
> 
> So it makes it impossible for me to run integration tests if my current namespace contains other components.
> 
> I'm wondering if we shouldn't still set `KUBECONFIG` to a dummy file (`/dev/null` on Linux for example) if `NeedsCluster(CurrentSpecReport().Labels())` is `false`. What do you think?

Yes you are right, I also encountered this problem. 

I would be OK to declare KUBECONFIG=/dev/null for the `test-integration-no-cluster` entry in Makefile, but this will not work on Windows, and I cannot find a way to make it work in both Linux and Windows (declaring it to an unexisting file, like /tmp/notfound, does not work)

2022-11-18 15:11 UTC, feloy commented
> And how about doing so in [`helper_generic.go`](https://github.com/redhat-developer/odo/pull/6303/files#diff-fc9f10e747d3f882b5d6484a7d307e3a2e0afda5ea2ea5539f8e3d6d75bd5af0)? That was my initial thought. When a cluster is needed, we are actually copying the current kubeconfig to a dedicated directory and setting the `KUBECONFIG` env var to it. So in case a cluster is not needed, maybe we could generate a temporary empty file and set the `KUBECONFIG` env var to it?

Good idea, an empty file should do the trick, thanks. Let me try

2022-11-18 16:31 UTC, rm3l approved these changes
Thanks for the changes.

2022-11-21 10:10 UTC, rm3l approved these changes

2022-11-21 15:34 UTC, rm3l approved these changes

2022-11-21 15:35 UTC, rm3l commented
/approve

2022-11-21 15:38 UTC, feloy commented
I added an acceptance criteria "It should test on an environment without cluster that commands needing a cluster are failing correctly with an appropriate message" in Issue #6237 to cover all commands in a similar way it is done here for odo describe/list component / odo dev

2022-11-21 16:02 UTC, feloy commented
/override v4.11-integration-e2e
Tests pass on IBM Cloud

2022-11-21 16:03 UTC, feloy commented
/override ci/prow/v4.11-integration-e2e

2022-11-21 16:06 UTC, merged