[WIP] odo list component shows components running on podman
redhat-developer/odo pull request #6366
Opened 2022-12-01 09:20 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6297 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-12-05 08:50 UTC, feloy commented
Blocked by #6374

2022-12-05 10:50 UTC, rm3l commented on pkg/podman/version.go
> +	out, err := exec.Command(o.podmanCmd, "version", "--format", "json").Output()
Wondering if we shouldn't `klog` the actual command that will be launched (here and everywhere we are running `podman`).
I didn't remember I had set `export PODMAN_CMD=docker` on my system some time ago. And the error message (even with increased verbosity) was not really helpful in understanding the error.

```
$ ODO_EXPERIMENTAL_MODE=true odo dev --run-on=podman --debug --no-watch
Experimental mode enabled for flag: --run-on. Use at your own risk. More details on https://odo.dev/docs/user-guides/advanced/experimental-mode
 ✗  unable to access podman. Do you have podman client installed?
```

2022-12-05 15:32 UTC, rm3l requested changes

2022-12-05 15:32 UTC, rm3l commented on pkg/odo/cli/list/component/list.go
> +			row = append(row, comp.RunningOn)
To be consistent in the human-readable form, can we display something like `None` when `comp.RunningOn` is empty?

```
$ ODO_EXPERIMENTAL_MODE=true odo list component
Experimental mode enabled for flag: --run-on. Use at your own risk. More details on https://odo.dev/docs/user-guides/advanced/experimental-mode
 ✓  Listing components from namespace 'default' [210ms]
 NAME                                       PROJECT TYPE  RUNNING IN   MANAGED       RUNNING ON 
 my-nodesjs-with-k8s-uri-with-var           nodejs        Dev, Deploy  odo (v3.3.0)  cluster    
 my-nodejs-app-with-composite-run-commands  nodejs        Dev          odo (v3.3.0)  cluster    
 * a-test-nodejs                            Node.js       None         Unknown                  

```

2022-12-05 15:32 UTC, rm3l commented on pkg/podman/podman.go
> +	klog.V(3).Infof("executing %v", cmd.Args)
Same point about logging before running the command..

2022-12-05 15:32 UTC, rm3l commented on pkg/podman/podman.go
> +	klog.V(3).Infof("executing %v", cmd.Args)
Same point about logging before running the command..

2022-12-05 15:32 UTC, rm3l commented on pkg/podman/podman.go
> +	klog.V(3).Infof("executing %v", cmd.Args)
Same point about logging before running the command..

2022-12-05 15:32 UTC, rm3l commented on pkg/podman/podman.go
> +	klog.V(3).Infof("executing %v", cmd.Args)
Same point about logging before running the command..

2022-12-06 15:22 UTC, rm3l approved these changes
Thanks - works great for me!

2022-12-06 15:45 UTC, feloy commented
/override ci/prow/v4.11-integration-e2e

2022-12-06 16:01 UTC, merged