Display a warning when connection to cluster fails
redhat-developer/odo pull request #6384
Opened 2022-12-07 10:09 UTC by feloy

**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

This PR makes `odo describe component` display a warning (in non-json output mode) when an error occurs when trying to get ingresses/routes, and not fail.

For the moment, is warning is not returned to json output, the error is just ignored.

**Which issue(s) this PR fixes:**

Fixes #6379 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

```
$ odo logout
$ odo describe component 
 ⚠  failed to get ingresses/routes: ingresses.networking.k8s.io is forbidden: User "system:anonymous" cannot list resource "ingresses" in API group "networking.k8s.io" in the namespace "prj3"
Name: empty
Display Name: Go Runtime
Project Type: Go
Language: Go
Version: 1.0.2
Description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
Tags: Go

Running in: None

Supported odo features:
 •  Dev: true
 •  Deploy: false
 •  Debug: false

Container components:
 •  runtime
```

2022-12-08 05:36 UTC, valaparthvi approved these changes
When logged out of the cluster, `odo describe component` without Devfile instantly returns a NoComponentFoundError because it could not determine the running mode. Do you think we can implement a similar warning for this case as well?

2022-12-08 05:39 UTC, valaparthvi requested changes
Can you add an integration/unit test for this case, it looks like a regression from Denis' comments?
You can use the devfile-deploy-route.yaml.

2022-12-08 11:07 UTC, rm3l requested changes
> What type of PR is this:
>
> /kind bug
>
> What does this PR do / why we need it:
> 
> This PR makes odo describe component display a warning (in non-json output mode) when an error occurs when trying to get ingresses/routes, and not fail.
> 
> For the moment, is warning is not returned to json output, the error is just ignored.
>

Are we sure the error is being ignored in JSON output? I can still see an error returned:
```
$ odo describe component -o json
{
        "message": "failed to get ingresses/routes: ingresses.networking.k8s.io is forbidden: User \"system:anonymous\" cannot list resource \"ingresses\" in API group \"networking.k8s.io\" in the namespace \"rh-ee-asoro-dev\""
}

x echo $?                                                                               
1
```

2022-12-08 12:00 UTC, feloy commented
> > What type of PR is this:
> > /kind bug
> > What does this PR do / why we need it:
> > This PR makes odo describe component display a warning (in non-json output mode) when an error occurs when trying to get ingresses/routes, and not fail.
> > For the moment, is warning is not returned to json output, the error is just ignored.
> 
> Are we sure the error is being ignored in JSON output? I can still see an error returned:

My bad :( I fixed the problem

2022-12-08 12:01 UTC, feloy commented
> Can you add an integration/unit test for this case, it looks like a regression from Denis' comments? You can use the devfile-deploy-route.yaml.

I'll work on having a test environment for this

2022-12-08 16:30 UTC, feloy commented
/hold
Blocked by #6395

2022-12-08 16:32 UTC, rm3l commented
LGTM as well - thanks @feloy!

Will the tests be added as part of this PR or in #6395?

2022-12-08 16:36 UTC, rm3l approved these changes

2022-12-09 12:51 UTC, rm3l approved these changes

2022-12-09 13:18 UTC, feloy commented
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests
Unrelated flaky test

```
odo dev command tests
/go/odo_1/tests/integration/cmd_dev_test.go:31
  port-forwarding for the component
  /go/odo_1/tests/integration/cmd_dev_test.go:595
    when devfile has single endpoint
    /go/odo_1/tests/integration/cmd_dev_test.go:596
      when running odo dev
      /go/odo_1/tests/integration/cmd_dev_test.go:605
        when modifying memoryLimit for container in Devfile [BeforeEach]
        /go/odo_1/tests/integration/cmd_dev_test.go:639
          should expose the endpoint on localhost
          /go/odo_1/tests/integration/cmd_dev_test.go:655
```

2022-12-09 14:19 UTC, rm3l commented
/override ci/prow/v4.11-integration-e2e

```
-----------------------------
• [FAILED] [0.520 seconds]
odo devfile supported tests [BeforeEach]
/go/src/github.com/redhat-developer/odo/tests/e2escenarios/e2e_devfile_test.go:26
  odo debug support for devfile components
  /go/src/github.com/redhat-developer/odo/tests/e2escenarios/e2e_devfile_test.go:67
    Verify output debug information for java-maven debug works
    /go/src/github.com/redhat-developer/odo/tests/e2escenarios/e2e_devfile_test.go:77
...
[oc] error: failed to create configmap: configmaps is forbidden: User "developer" cannot create resource "configmaps" in API group "" in the namespace "e2e-devfile-test77vxw"
...
 No future change is possible.  Bailing out early - after 0.051s.
  Running oc with args [oc create configmap config-map-for-cleanup --from-literal type=testing --from-literal team=odo -n e2e-devfile-test77vxw] and odo env: []
  Expected
      <int>: 1
  to match exit code:
      <int>: 0
  In [BeforeEach] at: /go/src/github.com/redhat-developer/odo/tests/helper/helper_cmd_wrapper.go:101
```

Same E2E test passed on IBM Cloud OpenShift cluster.

2022-12-09 14:23 UTC, merged