Change wording for dev/deploy
redhat-developer/odo pull request #6408
Opened 2022-12-14 08:32 UTC by feloy

**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6387

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-12-15 09:39 UTC, feloy commented
These changes will modify lots of commands outputs displayed in doc. 
Blocked by #6192

2023-01-09 15:11 UTC, rm3l requested changes

2023-01-09 15:11 UTC, rm3l commented on cmd/odo/help_test.go
> +  deploy       Run components in Deploy mode
To be consistent with the help message for `dev`:

```suggestion
  deploy       Run your application on the cluster in the Deploy mode
```

2023-01-09 17:22 UTC, rm3l approved these changes

2023-01-09 18:51 UTC, feloy commented
/override OpenShift-Integration-tests/OpenShift-Integration-tests
Flaky e2e test

2023-01-09 19:28 UTC, feloy commented
/override ci/prow/v4.11-integration-e2e

2023-01-09 19:34 UTC, merged