odo delete component on podman with --name
redhat-developer/odo pull request #6437
Opened 2022-12-22 16:25 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

`odo delete component` on podman with `--name`

**Which issue(s) this PR fixes:**

Fixes #6296 

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2022-12-23 07:20 UTC, valaparthvi requested changes

2022-12-23 07:20 UTC, valaparthvi commented on pkg/odo/cli/delete/component/component.go
> +	}
Can you could modify `printDevfileComponents` to print podman resources as well so that the output is similar for both devfile and podman resources?

2022-12-23 07:20 UTC, valaparthvi commented on pkg/odo/cli/delete/component/component.go
> +			log.Infof("The component %q is successfully deleted from podman", o.name)
```suggestion
			log.Infof("The component %q is successfully deleted from podman", componentName)
```

2022-12-23 07:20 UTC, valaparthvi commented on pkg/odo/cli/delete/component/component.go
> +				err = o.clientset.PodmanClient.CleanupPodResources(pod)
Optional:
It takes a few seconds to cleanup the pod resources, I think adding a spinner here would be a good idea.

2022-12-23 13:56 UTC, valaparthvi requested changes

2022-12-23 13:56 UTC, valaparthvi commented on pkg/odo/cli/delete/component/component.go
>  	log.Infof("This will delete %q from the namespace %q.", componentName, namespace)
Can you fix this message to also indicate podman if podmanResources are present?

2023-01-02 06:28 UTC, valaparthvi approved these changes

2023-01-02 10:40 UTC, feloy commented
/override ci/prow/v4.11-integration-e2e
Flaky e2e test

2023-01-02 10:44 UTC, merged