Implement `odo delete component --running-in`
redhat-developer/odo pull request #6485
Opened 2023-01-11 15:47 UTC by rm3l

**What type of PR is this:**
/kind feature

**What does this PR do / why we need it:**
See #6409 for the rationale.

**Which issue(s) this PR fixes:**
Fixes #6409 

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**
- The existing behavior is not altered. If `running-in` is not specified, `odo delete component` deletes resources running in both `dev` and `deploy`. If the experimental mode is on, it also tries to delete resources deployed on Podman.
- Use `odo delete component --running-in <dev|deploy>`.
- It works with or without the `--name` flag, and on Podman as well.

2023-01-13 10:05 UTC, valaparthvi requested changes

2023-01-13 10:07 UTC, valaparthvi commented on docs/website/docs/command-reference/delete-component.md
> +```
Can you add this to `command-reference/docs-mdx/delete/<filename>.mdx` so that it can be later used for test automation?

2023-01-13 10:08 UTC, valaparthvi commented on docs/website/docs/command-reference/delete-component.md
> +```
Can you add this to command-reference/docs-mdx/delete/<filename>.mdx so that it can be later used for test automation?

2023-01-16 08:58 UTC, rm3l commented on tests/integration/cmd_delete_test.go
> +				})
I've updated this test to make it less confusing.

2023-01-16 13:32 UTC, rm3l commented
/hold

`odo list` tests on Podman are not passing because it seems they are run after the `odo delete component` tests (which currently might not delete everything when using the new `--running-in` flag); so `odo list` on Podman is finding more resources than needed because there is no resource isolation on Podman.
Looking into this issue..

2023-01-18 08:20 UTC, rm3l commented
Blocked by #6499, which should allow running Podman tests in isolated namespaces.

2023-01-23 16:15 UTC, rm3l commented
/hold cancel

2023-01-23 17:06 UTC, feloy approved these changes

2023-01-23 20:43 UTC, rm3l commented
Rebased and force-pushed to fix Git conflicts.

2023-01-23 21:04 UTC, feloy approved these changes

2023-01-23 22:50 UTC, merged