Fix failing tests due to notifications related to update in output
redhat-developer/odo pull request #6625
Opened 2023-02-28 08:26 UTC by ritudes

**What type of PR is this:**

/area testing

**What does this PR do / why we need it:**
->It fixes the issue of failing tests due to the display of update notifications in the output.

**Which issue(s) this PR fixes:**

Fixes #6618 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2023-02-28 13:51 UTC, rm3l reviewed
@ritudes @anandrkskd LGTM to me, but besides this and to avoid similar issues in the future, can we also change the checks in those tests to make them less strict?
As discussed in https://github.com/redhat-developer/odo/issues/6618#issuecomment-1440244343, we should not expect an exact match, but it should be fine if we check that the output just contains the expected string.

2023-03-01 06:25 UTC, anandrkskd commented
>  it should be fine if we check that the output just contains the expected string.
You mean to use the func `BeEquivalentTo` instead of what we are using right now in our checks ?

2023-03-01 08:20 UTC, rm3l commented
> > it should be fine if we check that the output just contains the expected string.
> 
> You mean to use the func `BeEquivalentTo` instead of what we are using right now in our checks ?

The failing tests reported in https://github.com/redhat-developer/odo/issues/6618#issue-1595197802 are currently too strict, IMO, because they are using [`BeEquivalentTo`](https://onsi.github.io/gomega/#beequivalenttoexpected-interface) (which expects the actual value to be kind of equal to the expected value). I think we could be less strict by using `ContainSubstring` instead.

2023-03-01 09:55 UTC, anandrkskd commented
> I think we could be less strict by using ContainSubstring instead.

understood, Thanks @rm3l 
will make updates

2023-03-02 15:41 UTC, rm3l requested changes
A few comments on `cmd_devfile_build_images_test.go`

2023-03-02 15:41 UTC, rm3l commented on tests/integration/cmd_devfile_build_images_test.go
> +						Expect(lines[nbLines-2]).To(ContainSubstring(
I think checking an exact line number to match might be still a bit fragile, so I'd suggest checking that `stdout` contains the expected string:

```suggestion
						Expect(stdout).To(ContainSubstring(
```

2023-03-02 15:41 UTC, rm3l commented on tests/integration/cmd_devfile_build_images_test.go
> +						Expect(lines[nbLines-2]).To(ContainSubstring(
I think checking an exact line number to match might be still a bit fragile, so I'd suggest checking that `stdout` contains the expected string:

```suggestion
						Expect(stdout).To(ContainSubstring(
```

2023-03-03 08:40 UTC, rm3l approved these changes
Thanks for the changes, @anandrkskd and @ritudes!

2023-03-03 08:42 UTC, rm3l commented
```
user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  Expected
      <string>:   (
        	"""
        	... // 9 identical lines
        	â€¢  Waiting for Kubernetes resources  ...
        	âš   Pod is Pending
      - 	âœ“  Pod is Running
        	âœ“  Syncing files into the container [1s]
        	âœ“  Building your application in container (command: build) [1s]
        	... // 9 identical lines
        	[Ctrl+c] - Exit and delete resources from the cluster
        	[p] - Manually apply local changes to the application on the cluster
      + 	âœ“  Pod is Running
        	```
        	"""
        )
      
  to be empty
  In [It] at: /go/odo_1/tests/documentation/user-guides/doc_user_guides_quickstart_test.go:208
```

To be addressed by https://github.com/redhat-developer/odo/pull/6545

/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests

2023-03-03 08:47 UTC, merged