Speedup odo registry --details
redhat-developer/odo pull request #6678
Opened 2023-03-23 15:04 UTC by feloy

**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6401 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2023-03-24 09:38 UTC, valaparthvi requested changes
Changes lgtm, and the speed is visible. One small change is to remove reference to `devfileData` from [L132](https://github.com/redhat-developer/odo/pull/6678/files#diff-76ab00d8197655b21bc58d22d4ab8fd3d46a44a00fc14fc4607e3afba0f35bc7R132).

2023-03-24 15:04 UTC, rm3l requested changes
/hold

> A side-effet is that the stack content is not available anymore in the JSON output of the command. This removal will break the IDE plugins.

Indeed, I think we'll need to check with the IDE plugins or find a way not to break the output structure..

After a quick [search](https://github.com/search?q=repo%3Aredhat-developer%2Fvscode-openshift-tools+devfileData&type=code) into the source code, the VSCode plugin seems to rely on the `.devfileData.devfile` field from the `odo registry --details` output. 
See:
- https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/registriesView.ts#L141-L151
- https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/odo/command.ts#L285-L294

2023-03-24 16:15 UTC, feloy commented
> /hold
> 
> > A side-effet is that the stack content is not available anymore in the JSON output of the command. This removal will break the IDE plugins.
> 
> Indeed, I think we'll need to check with the IDE plugins or find a way not to break the output structure..
> 
> After a quick [search](https://github.com/search?q=repo%3Aredhat-developer%2Fvscode-openshift-tools+devfileData&type=code) into the source code, the VSCode plugin seems to rely on the `.devfileData.devfile` field from the `odo registry --details` output. See:
> 
> * https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/registriesView.ts#L141-L151
> * https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/odo/command.ts#L285-L294

Yes, right. These lines particularly are using the `supportedOdoFeatures` which are removed by the current patch.

https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/openshift/component.ts#L108-L110

Also the devfileData.devfile.metadata.name used in many places, for example 
https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/openshift/component.ts#L386

2023-03-28 13:18 UTC, feloy commented
I've made changes according to what has been discussed during cabal. See https://github.com/redhat-developer/odo/pull/6678#issue-1637723214 for more details.

2023-03-29 13:15 UTC, rm3l requested changes

2023-03-29 13:15 UTC, rm3l commented on pkg/api/registry.go
> +	CommandGroups   map[schema.CommandGroupKind]bool
To follow the field naming convention in the JSON output:

```suggestion
	CommandGroups   map[schema.CommandGroupKind]bool `json:"commandGroups,omitempty"`
```

2023-03-29 13:15 UTC, rm3l commented on pkg/odo/cli/registry/registry.go
> +	return api.DevfileStackVersion{}, errors.New("version not found")
To help understand the error:

```suggestion
	return api.DevfileStackVersion{}, fmt.Errorf("version %q not found in Devfile stack for %q", v, stack.Name)
```

2023-03-29 15:57 UTC, rm3l reviewed
LGTM, but maybe you can also add a note to the `odo registry` command reference page, just to mention that `--details` is intended to be used with `--devfile`? Currently, it reads "`--details` to display details about the Devfile stacks", which is not clear enough..

https://odo.dev/docs/command-reference/registry

2023-03-30 06:12 UTC, feloy commented
/override OpenShift-Integration-tests/OpenShift-Integration-tests

Non related flaky test
```
[FAILED] [266.696 seconds]
odo dev command tests port-forwarding for the component when devfile has single endpoint when running odo dev when modifying memoryLimit for container in Devfile [BeforeEach] should react on the Devfile modification
  [BeforeEach] /go/odo_1/tests/integration/cmd_dev_test.go:800
  [It] /go/odo_1/tests/integration/cmd_dev_test.go:820
```

2023-04-03 09:29 UTC, rm3l approved these changes

2023-04-03 10:04 UTC, feloy commented
/override windows-integration-test/Windows-test
Flaky test

2023-04-03 10:49 UTC, rm3l commented on docs/website/docs/command-reference/json-output.md
>  odo registry --devfile java-springboot --details -o json
Can you also update the sample output below to include the new `versions.commandGroups` fields?

2023-04-03 11:08 UTC, rm3l commented on docs/website/docs/command-reference/json-output.md
>  odo registry --devfile java-springboot --details -o json
Whoops, I think we'll also need the same thing for the sample output of `odo registry -o json` above.

2023-04-03 11:56 UTC, rm3l approved these changes

2023-04-03 12:24 UTC, feloy commented
> Sounds good to me to remove the hold on this PR, now that we are pretty confident in not breaking the IDE plugins, no? What do you think? I added a reminder to document the deprecated `odo registry --details` (without `--devfile`) in the [v3.9.0](https://github.com/redhat-developer/odo/issues/6643) release notes too.

Yes, the JSON output is not changed by this patch, it should not break the IDE plugins

2023-04-03 12:37 UTC, rm3l commented
> > Sounds good to me to remove the hold on this PR, now that we are pretty confident in not breaking the IDE plugins, no? What do you think? I added a reminder to document the deprecated `odo registry --details` (without `--devfile`) in the [v3.9.0](https://github.com/redhat-developer/odo/issues/6643) release notes too.
> 
> Yes, the JSON output is not changed by this patch, it should not break the IDE plugins

Thanks for confirming.

/hold cancel

2023-04-03 13:24 UTC, feloy commented
/override OpenShift-Integration-tests/OpenShift-Integration-tests

Flaky e2e test

```
 [FAILED] [212.271 seconds]
E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
/go/odo_1/tests/e2escenarios/e2e_test.go:337
```

2023-04-03 14:05 UTC, merged