Disable service binding related integration tests
redhat-developer/odo pull request #6920
Opened 2023-06-21 14:13 UTC by feloy

**What type of PR is this:**

/area testing

The purpose of this PR is to test the impact of removing the integration tests related to service binding.

2023-06-22 11:22 UTC, valaparthvi requested changes
e2e_test.go:`Context("starting with non-empty Directory add Binding", func() {`
 can use skipping.

2023-06-22 11:25 UTC, feloy commented
> e2e_test.go:`Context("starting with non-empty Directory add Binding", func() {` can use skipping.

No, I would like to keep the tests for e2e tests.

2023-06-22 11:27 UTC, valaparthvi commented
>Also, wouldn't you need to modify IBM pipelines to export the env var? I believe the tests are still run on OpenShift, since I do not see any difference between the number of k8s and oc tests.

In case you missed.

2023-06-22 11:28 UTC, feloy commented
> > Also, wouldn't you need to modify IBM pipelines to export the env var? I believe the tests are still run on OpenShift, since I do not see any difference between the number of k8s and oc tests.
> 
> In case you missed.

I defined the env var in the pipelines, but after the job has been created. It seems the env variables are considered at the time the job is created (not the time it is started).

Let me try again

2023-06-23 14:16 UTC, rm3l approved these changes

2023-06-23 16:17 UTC, feloy commented
/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests
```
[FAILED] [74.869 seconds]
User guides: Quickstart test Java quickstart guide [It] should test the complete java springboot quickstart output in order
/go/odo_1/tests/documentation/user-guides/doc_user_guides_quickstart_test.go:217

  [odo]  âš   0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.

```

2023-06-23 16:20 UTC, merged