fix: manage podman inspect result as a list also
redhat-developer/odo pull request #7269
Opened 2024-10-09 16:02 UTC by too-common-name

**What type of PR is this:**

/kind bug
/area odo-on-podman

**What does this PR do / why we need it:**

This PR addresses an issue when using the `odo` commands with Podman, specifically related to the `podman pod inspect` command. Due to a recent change in Podman (see [podman PR #21514](https://github.com/containers/podman/pull/21514)), the output now returns a JSON array instead of a JSON object. This PR modifies `odo` to correctly handle this change, preventing errors in commands like `odo debug` and `odo logs` when running on Podman.

**Which issue(s) this PR fixes:**

Fixes #7252

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

2024-10-09 16:08 UTC, rm3l commented
/ok-to-test

2024-10-11 15:35 UTC, rm3l requested changes

2024-10-11 15:35 UTC, rm3l commented on pkg/podman/inspect.go
> +	return result[0], err
```suggestion
	if len(result) == 0 {
		return PodInspectData{}, nil
	}
	return result[0], nil
```

Just to be safe and avoid panicking if the list is empty for some reason.

2024-10-12 12:18 UTC, rm3l approved these changes
Thanks @too-common-name !!

2024-10-12 12:18 UTC, merged

2024-10-14 07:20 UTC, too-common-name commented
Thank you for merging this! This was my first contribution as a RedHatter, and I'm really excited to have been able to help improve odo. I hope this is just the first of many contributions to come. Looking forward to learning more and contributing further to the community!